services:
  - type: web
    name: whatsnext-auth-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        sync: false
      - key: DB_URL
        fromDatabase:
          name: whatsnext-auth-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: whatsnext-auth-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: whatsnext-auth-db
          property: password
      - key: CORS_ALLOWED_ORIGINS
        value: https://kevinaryeldev.github.io
    healthCheckPath: /actuator/health

databases:
  - name: whatsnext-auth-db
    databaseName: authapi
    plan: free
